sudo: false
language: minimal
env:
  - HUGO_VERSION="0.71.1"
install:
  - curl -fLo "$HOME/bin/hugo_extended_Linux-64bit.tar.gz" --create-dirs "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"
  - tar -xzf $HOME/bin/hugo_extended_Linux-64bit.tar.gz -C $HOME/bin
  - $HOME/bin/hugo version
script:
  - hugo --gc --minify
branches:
  only:
    - master
    - /^release.*$/
    - /^feature.*$/
    - /^hotfix.*$/  
