sudo: false
language: generic
go:
  - 1.13
install:
  - go get github.com/gohugoio/hugo
script:
  - hugo --gc --minify
branches:
  only:
  - master
  - /^release.*$/
  - /^feature.*$/
  - /^hotfix.*$/  
